package jojo.game.enums

enum class DataType {
    DEFAULT,
    LOGIN,

    PLAYER_INFO,

    ROOM_CREATE,
    ROOM_JOIN,
    ROOM_LEAVE,
    ROOM_SEARCH,
    ROOM_INFO,

    GAME_READY,
    GAME_START,
    GAME_RESULT,
    GAME_BET,
    GAME_DEAL_PLAYER_CARDS,
    GAME_DEAL_FLOP_CARDS,
    GAME_DEAL_TURN_CARDS,
    GAME_DEAL_RIVER_CARDS,
    GAME_UPDATE_BET,
    GAME_ROUND

}