apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"game-server":"my-backendconfig"}}'
  labels:
    app: super-holdem-server
  name: super-holdem-server-service
  namespace: super-holdem
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: game-server
      port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: 30088
    - name: auth-server
      port: 8887
      protocol: TCP
      targetPort: 8887
      nodePort: 30087
  selector:
    app: super-holdem-server
  sessionAffinity: None
  type: NodePort
